package com.example.cafebrown.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF482A20)
val md_theme_light_onPrimary = Color(0xFF5D1800)
val md_theme_light_primaryContainer = Color(0xFF7C2E11)
val md_theme_light_onPrimaryContainer = Color(0xFF512400)
val md_theme_light_secondary = Color(0xFFA15B27)
val md_theme_light_onSecondary = Color(0xFF512400)
val md_theme_light_secondaryContainer = Color(0xFF733600)
val md_theme_light_onSecondaryContainer = Color(0xFFFFDCC7)
val md_theme_light_tertiary = Color(0xFFfcdb63)
val md_theme_light_onTertiary = Color(0xFF3B2F00)
val md_theme_light_tertiaryContainer = Color(0xFF554500)
val md_theme_light_onTertiaryContainer = Color(0xFFFFE177)
val md_theme_light_error = Color(0xFFFFB4AB)
val md_theme_light_errorContainer = Color(0xFF93000A)
val md_theme_light_onError = Color(0xFF690005)
val md_theme_light_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_light_background = Color(0xFF281710)
val md_theme_light_onBackground = Color(0xFFFFDBD0)
val md_theme_light_surface = Color(0xFF3A0B00)
val md_theme_light_onSurface = Color(0xFFFFDBD0)
val md_theme_light_surfaceVariant = Color(0xFF53433F)
val md_theme_light_onSurfaceVariant = Color(0xFFD8C2BB)
val md_theme_light_outline = Color(0xFFA08D87)
val md_theme_light_inverseOnSurface = Color(0xFF3A0B00)
val md_theme_light_inverseSurface = Color(0xFFFFDBD0)
val md_theme_light_inversePrimary = Color(0xFF9B4426)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFFFB59D)
val md_theme_light_outlineVariant = Color(0xFF53433F)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB787)
val md_theme_dark_onPrimary = Color(0xFF512400)
val md_theme_dark_primaryContainer = Color(0xFF733600)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDCC7)
val md_theme_dark_secondary = Color(0xFFE5C44A)
val md_theme_dark_onSecondary = Color(0xFF3B2F00)
val md_theme_dark_secondaryContainer = Color(0xFF554500)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFE177)
val md_theme_dark_tertiary = Color(0xFFFFB59D)
val md_theme_dark_onTertiary = Color(0xFF5D1800)
val md_theme_dark_tertiaryContainer = Color(0xFF7C2E11)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDBD0)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF281710)
val md_theme_dark_onBackground = Color(0xFFFFDBD0)
val md_theme_dark_surface = Color(0xFF281710)
val md_theme_dark_onSurface = Color(0xFFFFDBD0)
val md_theme_dark_surfaceVariant = Color(0xFF52443C)
val md_theme_dark_onSurfaceVariant = Color(0xFFD7C3B8)
val md_theme_dark_outline = Color(0xFF9F8D83)
val md_theme_dark_inverseOnSurface = Color(0xFF3A0B00)
val md_theme_dark_inverseSurface = Color(0xFFFFDBD0)
val md_theme_dark_inversePrimary = Color(0xFF954A05)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB787)
val md_theme_dark_outlineVariant = Color(0xFF52443C)
val md_theme_dark_scrim = Color(0xFF57DCBB)


val seed = Color(0xFF482A20)